baseURL = "https://Dax-Um.github.io/"
languageCode = "ko-kr"
title = "Dax-Um의 성장 일기"
theme = "PaperMod"

[params]
  author = "Dax-Um"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Resume"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Android"
  url = "/categories/android"
  weight = 2

[[menu.main]]
  name = "Jetpack Compose"
  url = "/categories/jetpack-compose"
  weight = 3

[[menu.main]]
  name = "Kotlin"
  url = "/categories/kotlin"
  weight = 4

[[menu.main]]
  name = "Java"
  url = "/categories/java"
  weight = 5

[[menu.main]]
  name = "TDD"
  url = "/categories/tdd"
  weight = 6

[[menu.main]]
  name = "Architecture"
  url = "/categories/architecture"
  weight = 7

[params.assets]
customCSS = ["css/extended/custom.css"]