baseURL = "https://Dax-Um.github.io/"
languageCode = "ko-kr"
title = "Dax의 개발 서랍"
theme = "PaperMod"

[params]
  description = "소개글"
  ShowPostCards = true 
  ShowPageThumbnail = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  [params.homeInfoParams]
    content = "하루 하루 성장하고 싶은 안드로이드 개발자의 공부하며 겪었던 문제들을 차곡 차곡 모아 기록하고 꺼내보는 곳"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Algorithm"
  url = "/categories/Algorithm"
  weight = 1

[[menu.main]]
  name = "Android"
  url = "/categories/Android"
  weight = 2

[[menu.main]]
  name = "Jetpack Compose"
  url = "/categories/Jetpack Compose"
  weight = 3

[[menu.main]]
  name = "Java vs Kotlin"
  url = "/categories/Java vs Kotlin"
  weight = 4

[[menu.main]]
  name = "TDD & Architecture"
  url = "/categories/TDD & Architecture"
  weight = 5

[[menu.main]]
  name = "Side Project"
  url = "/categories/Side Project"
  weight = 6

[params.assets]
customCSS = ["css/extended/custom.css"]